site_name: 'Project:007 Document'
site_author: 'hzy'
site_description: 'Project007 Documentation'

edit_uri: 'docs/'

nav:
  - 系统策划案: index.md
  - 渲染大纲: 渲染/渲染大纲.md
  - 系统: 
    - 核心玩法: 核心玩法.md
    - 世界观背景: 故事板.md
  - 界面: 界面/界面.md
  - 关卡模块: 关卡模块/关卡.md
  - 道具模块: 道具模块/道具.md
  - 战斗模块 :
    - AI: 战斗模块/AI.md
    - 道具: 战斗模块/道具.md
    - 角色控制: 战斗模块/角色控制.md
    - 角色属性: 战斗模块/角色属性.md
    - 芯片模块: 战斗模块/芯片模块.md
    - 装备: 战斗模块/装备.md
  - 相机: 相机模块/相机模块.md
  - 项目配置: 项目配置.md

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  #- pymdownx.caret  # 下划线上标
  #- pymdownx.tilde  # 删除线下标
  #- pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  #- pymdownx.inlinehilite  # 行内代码高亮
  #- pymdownx.mark  # 文本高亮
  #- pymdownx.smartsymbols  # 符号转换
  #- pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  #- pymdownx.betterem:  # 对加粗和斜体更好的检测
  #    smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  #- pymdownx.tasklist:  # 复选框checklist
  #    custom_checkbox: true

theme: readthedocs
