site_name: Project:007 Document
site_author: 'hzy'
site_description: 'Project007 Documentation'

#edit_uri: 'Design/docs/'

nav:
- 系统策划案: "【系统策划案】代号：007.md"
- a01: "【会议小计】2022年08月21日22点23分.md"
- a02: "【会议小计】2022年08月20日01点26分.md"
- a03: "【笔记】demo玩法核心.md"  
- 战斗模块 :
  - 武器: 武器模块/武器.md
  - 芯片: 芯片模块/芯片.md
  - 角色控制: 角色控制模块/角色控制.md
- 相机: 相机模块/相机模块.md

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  #- pymdownx.caret  # 下划线上标
  #- pymdownx.tilde  # 删除线下标
  #- pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  #- pymdownx.details  # 提示块可折叠
  #- pymdownx.inlinehilite  # 行内代码高亮
  #- pymdownx.mark  # 文本高亮
  #- pymdownx.smartsymbols  # 符号转换
  #- pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  #- pymdownx.betterem:  # 对加粗和斜体更好的检测
  #    smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  #- pymdownx.tasklist:  # 复选框checklist
  #    custom_checkbox: true

theme: readthedocs
